services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: alineo
      POSTGRES_PASSWORD: alineo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
